namespace projectcars.Contracts.Cars;

public record FiltredCarsRequest
(
    double? MaxPrice,
    double? MaxEngineVolume,
    string? TransmissionType,
    string? BodyType,
    string? EngineType,
    string? DriveTrain,
    int? MaxEnginePower,
    int? MaxMileage,
    string? Color,
    string? InteriorColor,
    string? InteriorMaterial,
    string? Description,
    string? CarState,
    string? RegistrationCountry,
    int? MinYear,
    int? MaxYear,
    Guid? GenerationId,
    Guid? ModelId,
    Guid? BrandId,
    Guid? CityId,
    double? MinPrice,
    double? MinEngineVolume,
    int? MinEnginePower,
    int? MinMileage,
    int Take = 2,
    int Skip = 0,
    bool TowBar = false,
    bool RoofRails = false,
    bool SunRoof = false,
    bool PanoramicRoof = false,
    bool RainSensor = false,
    bool RearViewCamera = false,
    bool ParkingSensors = false,
    bool BlindSpotSensor = false,
    bool HeatedSeats = false,
    bool HeatedWindshield = false,
    bool HeatedMirrors = false,
    bool HeatedSteeringWheel = false,
    bool AutonomousHeater = false,
    bool ClimateControl = false,
    bool AirConditioner = false,
    bool CruiseControl = false,
    bool SteeringWheelMultimedia = false,
    bool ElectricSeats = false,
    bool FrontElectroWindows = false,
    bool RearElectroWindows = false,
    bool AirBags = false,
    bool IsTradable = false,
    bool IsRegistred = false,
    bool Abs = false,
    bool Esp = false,
    bool Asr = false,
    bool Immobilizer = false,
    bool Signaling = false
);
